name: WarpX
version: '0.1'
main: me.nullapex.warpX.WarpX
api-version: '1.21'
load: STARTUP
authors: [ NullApex, aoitcl ]
description: WarpX a minecraft warping plugin
website: https://github.com/NullApexMC/WarpX
